#!/usr/bin/env python
#
# g2cam -- instrument using OCS Gen2 interface
#
# Eric Jeschke (eric@naoj.org)
#
from __future__ import print_function

# stdlib imports
import sys, os
import signal
import threading
import logging
import traceback
# profile imported below (if needed)
# pdb imported below (if needed)
# optparse imported below (if needed)

# g2base imports
from g2base import Task, ssdlog
from g2base.remoteObjects import remoteObjects as ro
from g2base.remoteObjects import Monitor

# module imports
from g2cam.Instrument import Instrument
from g2cam import version

# Add "cams" directory to our search path for loading cams
sys.path.insert(0, "./cams")


def main(options, args):

    # Several cameras can be specified with the --cam option
    # "main" camera is the last one on the list
    cams = options.cam.split(',')
    maincam = cams[-1]
    if '=' in maincam:
        (alias, maincam) = maincam.split('=')
    maincam = maincam.upper()

    # Create top level logger.
    logger = ssdlog.make_logger(maincam, options)

    ev_quit = threading.Event()

    # Determine the personalities.  User can specify several cams to be
    # loaded on the command line.  Also, cams can be given aliases.
    camlist = []
    main_alias = 'SIMCAM'
    if options.cam:
        for cam in cams:
            alias = cam
            if '=' in cam:
                (alias, cam) = cam.split('=')
            camlist.append((alias, cam))

        main_alias = camlist[0][0]

    svcname = main_alias

    # Create Gen2 interfaces
    try:
        ro.init([options.gen2host])

    except ro.remoteObjectError as e:
        logger.error("Cannot initialize remote objects: %s" % str(e))
        sys.exit(1)

    frameint = ro.remoteObjectProxy(options.framesvc)
    statusint = ro.remoteObjectProxy(options.statussvc)
    archiveint = ro.remoteObjectProxy(options.archivesvc)
    viewerint = ro.remoteObjectProxy(options.viewersvc)

    # Create process-wide thread pool for autonomous tasks
    threadPool = Task.ThreadPool(logger=logger, ev_quit=ev_quit,
                                 numthreads=options.numthreads)

    # Create monitor for PubSub style feedback
    monitor = Monitor.Monitor('%s.mon' % svcname, logger,
                              ev_quit=ev_quit, threadPool=threadPool)
    cmdchannel = 'INSint%d' % options.obcpnum

    # Create the instrument object
    caminst = Instrument(logger, threadPool, monitor,
                         [cmdchannel], ev_quit=ev_quit,
                         archiveint=archiveint, frameint=frameint,
                         statusint=statusint, viewerint=viewerint,
                         obcpnum=options.obcpnum)

    # Load the personalities.  User can specify several cams to be loaded
    # on the command line.  Also, cams can be given aliases.
    for (alias, cam) in camlist:
        caminst.loadPersonality(cam, alias=alias)

    channels = [cmdchannel, 'sound']
    if options.monitor:
        # Publish our channels to the specified monitor
        monitor.publish_to(options.monitor, channels, {})

        # and subscribe to information about tasks
        taskch = [options.taskmgr, 'g2task']
        monitor.subscribe_cb(caminst.arr_taskinfo, taskch)
        # Not unless needed--this causes a lot of network traffic
        #monitor.subscribe_remote(options.monitor, taskch, {})

    try:
        try:
            logger.debug("Starting threadPool ...")
            threadPool.startall(wait=True)

            logger.debug("Starting monitor ...")
            monitor.start(wait=True)
            monitor.start_server(port=options.monport, wait=True)

            # Configure logger for logging via our monitor
            if options.logmon:
                monitor.logmon(logger, options.logmon, ['logs'])

            logger.info("Starting instrument %s ..." % maincam)
            caminst.start(portbase=options.port)

            # Run off and do my UI here...
            caminst.ui(main_alias, options, args, ev_quit)

        except KeyboardInterrupt:
            logger.error("Keyboard interrupt!")

        except Exception as e:
            logger.error("Exception starting instrument: %s" % str(e))
            try:
                (type, value, tb) = sys.exc_info()
                tb_str = "\n".join(traceback.format_tb(tb))

            except Exception:
                tb_str = "Traceback information unavailable."

            logger.error("Traceback:\n%s" % (tb_str))

    finally:
        if options.seppuku:
            logger.info("%s ... seppuku!" % maincam)
            os.kill(os.getpid(), signal.SIGKILL)

        logger.info("Stopping instrument %s ..." % maincam)
        caminst.stop()

        logger.debug("Stopping monitor ...")
        monitor.stop_server(wait=True)
        monitor.stop(wait=True)

        logger.debug("Stopping threadPool ...")
        threadPool.stopall(wait=True)


if __name__ == '__main__':

    # Parse command line options
    import argparse

    argprs = argparse.ArgumentParser()

    argprs.add_argument("--archivesvc", dest="archivesvc", metavar="NAME",
                        default='archiver',
                        help="Lookup archive service by NAME")
    argprs.add_argument("--cam", dest="cam", default="SIMCAM",
                        help="Use CAM as the instrument", metavar="CAM")
    argprs.add_argument("--debug", dest="debug", default=False, action="store_true",
                        help="Enter the pdb debugger on main()")
    argprs.add_argument("--display", dest="display", metavar="HOST:N",
                        help="Use X display on HOST:N")
    argprs.add_argument("--gen2host", dest="gen2host", metavar="HOST",
                        default='localhost',
                        help="Use HOST to dynamically locate services")
    argprs.add_argument("--framesvc", dest="framesvc", metavar="NAME",
                        default='frames',
                        help="Lookup frame service by NAME")
    argprs.add_argument("--monitorsvc", dest="monitor", metavar="NAME",
                        default='monitor',
                        help="Publish events to external monitor NAME")
    argprs.add_argument("--monport", dest="monport", type=int,
                        default=9080, metavar="NUM",
                        help="Use port number NUM for monitor connections")
    argprs.add_argument("-n", "--obcpnum", dest="obcpnum", type=int,
                        default=9,
                        help="Use NUM as the OBCP number", metavar="NUM")
    argprs.add_argument("--numthreads", dest="numthreads", type=int,
                        default=200,
                        help="Use NUM threads in thread pool", metavar="NUM")
    argprs.add_argument("--port", dest="port", type=int,
                        default=9081, metavar="NUM",
                        help="Use port number NUM for command connections")
    argprs.add_argument("--profile", dest="profile", action="store_true",
                        default=False,
                        help="Run the profiler on main()")
    argprs.add_argument("--seppuku", dest="seppuku", action="store_true",
                        default=False,
                        help="Terminate the program forcefully on ^C")
    argprs.add_argument("--statussvc", dest="statussvc", metavar="NAME",
                        default='status',
                        help="Lookup status service by NAME")
    argprs.add_argument("--taskmgr", dest="taskmgr", metavar="NAME",
                        default='taskmgr0',
                        help="Connect to TaskManager with name NAME")
    argprs.add_argument("--viewersvc", dest="viewersvc", metavar="NAME",
                        default='fitsview',
                        help="Lookup viewer service by NAME")
    argprs.add_argument('-V', '--version', action='version',
                        version='%(prog)s {}'.format(version.version))
    ssdlog.addlogopts(argprs)

    (options, args) = argprs.parse_known_args(sys.argv[1:])

    if options.display:
        os.environ['DISPLAY'] = options.display

    if len(args) != 0:
        argprs.error("incorrect number of arguments")


    # Are we debugging this?
    if options.debug:
        import pdb

        pdb.run('main(options, args)')

    # Are we profiling this?
    elif options.profile:
        import profile

        print("%s profile:" % sys.argv[0])
        profile.run('main(options, args)')

    else:
        main(options, args)


# END
