#! /usr/bin/env python3
#

import sys
import os
import re

from g2cam.status.client import StatusClient


host = os.environ['GEN2_STATUS_DB_HOST']
user = os.environ['GEN2_STATUS_DB_USER']
pswd = os.environ['GEN2_STATUS_DB_PASS']

client = StatusClient(host=host, username=user, password=pswd)
client.connect()

res = client.fetch_all()

if len(sys.argv) > 1:
    regex = re.compile(sys.argv[1])
    res2 = [(key, val) for key, val in res.items() if regex.match(key)]

else:
    res2 = list(res.items())

# sort alphabetically
res2.sort(key=lambda x: x[0])

# align keys
max_n = max([len(x[0]) for x in res2])
fmt_s = "{:%d}: {}" % max_n
res3 = "\n".join([fmt_s.format(key, val) for key, val in res2])
print(res3)
