#! /usr/bin/env python
#
# ro_ps_svc -- remote object pub/sub service
#
import sys
import argparse

from g2base import ssdlog
from g2base.remoteObjects import PubSub


if __name__ == '__main__':

    argprs = argparse.ArgumentParser(description="Remote PubSub Service")

    argprs.add_argument("--config", dest="config", metavar="FILE",
                        help="Use configuration FILE for setup")
    argprs.add_argument("--debug", dest="debug", default=False,
                        action="store_true",
                        help="Enter the pdb debugger on main()")
    argprs.add_argument("--inlimit", dest="inlimit", type=int, default=20,
                        help="Limit incoming connections to NUM", metavar="NUM")
    argprs.add_argument("--numthreads", dest="numthreads", type=int,
                        default=100,
                        help="Use NUM threads", metavar="NUM")
    argprs.add_argument("--outlimit", dest="outlimit", type=int, default=6,
                        help="Limit outgoing connections to NUM", metavar="NUM")
    argprs.add_argument("--port", dest="port", type=int, default=None,
                        help="Register using PORT", metavar="PORT")
    argprs.add_argument("--profile", dest="profile", action="store_true",
                        default=False,
                        help="Run the profiler on main()")
    argprs.add_argument("--svcname", dest="svcname", metavar="NAME",
                        default='pubsub',
                        help="Register using NAME as service name")
    ssdlog.addlogopts(argprs)

    (options, args) = argprs.parse_known_args(sys.argv[1:])

    if len(args) != 0:
        argprs.error("incorrect number of arguments")


    # Are we debugging this?
    if options.debug:
        import pdb

        pdb.run('PubSub.main(options, args)')

    # Are we profiling this?
    elif options.profile:
        import profile

        print("%s profile:" % sys.argv[0])
        profile.run('PubSub.main(options, args)')

    else:
        PubSub.main(options, args)
