#! /usr/bin/env python
#
# ro_ps_svc -- remote object pub/sub service
#
import sys
import argparse

from g2base import ssdlog
from g2base.remoteObjects import PubSub
from g2base.remoteObjects import remoteObjects as ro


if __name__ == '__main__':

    argprs = argparse.ArgumentParser(description="Remote PubSub Service")

    argprs.add_argument("--config", dest="config", metavar="FILE",
                        help="Use configuration FILE for setup")
    argprs.add_argument("--debug", dest="debug", default=False,
                        action="store_true",
                        help="Enter the pdb debugger on main()")
    argprs.add_argument("--inlimit", dest="inlimit", type=int, default=20,
                        help="Limit incoming connections to NUM", metavar="NUM")
    argprs.add_argument("--minthreads", dest="minthreads", type=int,
                        default=4,
                        help="Keep at least NUM threads, growing to "
                        "--numthreads as calls arrive", metavar="NUM")
    argprs.add_argument("--numthreads", dest="numthreads", type=int,
                        default=100,
                        help="Use at most NUM threads", metavar="NUM")
    argprs.add_argument("--outlimit", dest="outlimit", type=int, default=6,
                        help="Limit outgoing connections to NUM", metavar="NUM")
    argprs.add_argument("--port", dest="port", type=int, default=None,
                        help="Register using PORT", metavar="PORT")
    argprs.add_argument("--profile", dest="profile", action="store_true",
                        default=False,
                        help="Run the profiler on main()")
    argprs.add_argument("--svcname", dest="svcname", metavar="NAME",
                        default='pubsub',
                        help="Register using NAME as service name")
    argprs.add_argument("--transport", dest="transport", metavar="NAMES",
                        default=','.join(ro.compat_transports),
                        help="Listen these ways, most widely spoken first. "
                        "Unlike a pubsub embedded in a service, this one is "
                        "shared by publishers and subscribers of both ages, "
                        "so it answers both by default.  'g2rpc-tcp-asyncio' "
                        "serves from an event loop instead of a thread per "
                        "connection")
    ssdlog.addlogopts(argprs)

    (options, args) = argprs.parse_known_args(sys.argv[1:])

    if len(args) != 0:
        argprs.error("incorrect number of arguments")


    # Are we debugging this?
    if options.debug:
        import pdb

        pdb.run('PubSub.main(options, args)')

    # Are we profiling this?
    elif options.profile:
        import profile

        print("%s profile:" % sys.argv[0])
        profile.run('PubSub.main(options, args)')

    else:
        PubSub.main(options, args)
